from ..models import db, Friend, environment, SCHEMA
from sqlalchemy.sql import text


def seed_friends():
    friend1 = Friend(user_to=2, user_from=1, status="FRIENDS")
    friend2 = Friend(user_to=3, user_from=1)
    friend3 = Friend(user_to=4, user_from=1)
    friend4 = Friend(user_to=5, user_from=1, status="FRIENDS")
    friend5 = Friend(user_to=6, user_from=1, status="FRIENDS")

    friend6 = Friend(user_to=1, user_from=2, status="FRIENDS")
    friend7 = Friend(user_to=3, user_from=2, status="FRIENDS")
    friend8 = Friend(user_to=4, user_from=2, status="FRIENDS")
    friend9 = Friend(user_to=5, user_from=2)
    friend10 = Friend(user_to=6, user_from=2)

    friend11 = Friend(user_to=1, user_from=3)
    friend12 = Friend(user_to=2, user_from=3, status="FRIENDS")
    friend13 = Friend(user_to=4, user_from=3, status="FRIENDS")
    friend14 = Friend(user_to=5, user_from=3, status="FRIENDS")
    friend15 = Friend(user_to=6, user_from=3)

    friend16 = Friend(user_to=1, user_from=4)
    friend17 = Friend(user_to=2, user_from=4, status="FRIENDS")
    friend18 = Friend(user_to=3, user_from=4, status="FRIENDS")
    friend19 = Friend(user_to=5, user_from=4)
    friend20 = Friend(user_to=6, user_from=4)

    friend21 = Friend(user_to=1, user_from=5, status="FRIENDS")
    friend22 = Friend(user_to=2, user_from=5)
    friend23 = Friend(user_to=3, user_from=5, status="FRIENDS")
    friend24 = Friend(user_to=4, user_from=5)
    friend25 = Friend(user_to=6, user_from=5)

    friend26 = Friend(user_to=1, user_from=6, status="FRIENDS")
    friend27 = Friend(user_to=2, user_from=6)
    friend28 = Friend(user_to=3, user_from=6)
    friend29 = Friend(user_to=4, user_from=6)
    friend30 = Friend(user_to=5, user_from=6)

    friend31 = Friend(user_to=8, user_from=7, status="FRIENDS")
    friend32 = Friend(user_to=9, user_from=7, status="FRIENDS")
    friend33 = Friend(user_to=10, user_from=7)
    friend34 = Friend(user_to=11, user_from=7, status="FRIENDS")
    friend35 = Friend(user_to=12, user_from=7)

    friend36 = Friend(user_to=7, user_from=8, status="FRIENDS")
    friend37 = Friend(user_to=9, user_from=8, status="FRIENDS")
    friend38 = Friend(user_to=10, user_from=8)
    friend39 = Friend(user_to=11, user_from=8, status="FRIENDS")
    friend40 = Friend(user_to=12, user_from=8)

    friend41 = Friend(user_to=7, user_from=9, status="FRIENDS")
    friend42 = Friend(user_to=8, user_from=9, status="FRIENDS")
    friend43 = Friend(user_to=10, user_from=9, status="FRIENDS")
    friend44 = Friend(user_to=11, user_from=9)
    friend45 = Friend(user_to=12, user_from=9, status="FRIENDS")

    friend46 = Friend(user_to=7, user_from=10)
    friend47 = Friend(user_to=8, user_from=10)
    friend48 = Friend(user_to=9, user_from=10, status="FRIENDS")
    friend49 = Friend(user_to=11, user_from=10)
    friend50 = Friend(user_to=12, user_from=10)

    friend51 = Friend(user_to=7, user_from=11, status="FRIENDS")
    friend52 = Friend(user_to=8, user_from=11, status="FRIENDS")
    friend53 = Friend(user_to=9, user_from=11)
    friend54 = Friend(user_to=10, user_from=11)
    friend55 = Friend(user_to=12, user_from=11)

    friend56 = Friend(user_to=7, user_from=12)
    friend57 = Friend(user_to=8, user_from=12, status="FRIENDS")
    friend58 = Friend(user_to=9, user_from=12)
    friend59 = Friend(user_to=10, user_from=12)
    friend60 = Friend(user_to=11, user_from=12)

    friend61 = Friend(user_to=14, user_from=13)
    friend62 = Friend(user_to=15, user_from=13, status="FRIENDS")
    friend63 = Friend(user_to=16, user_from=13)
    friend64 = Friend(user_to=17, user_from=13, status="FRIENDS")
    friend65 = Friend(user_to=18, user_from=13)

    friend66 = Friend(user_to=13, user_from=14)
    friend67 = Friend(user_to=15, user_from=14, status="FRIENDS")
    friend68 = Friend(user_to=16, user_from=14, status="FRIENDS")
    friend69 = Friend(user_to=17, user_from=14, status="FRIENDS")
    friend70 = Friend(user_to=18, user_from=14)

    friend71 = Friend(user_to=13, user_from=15, status="FRIENDS")
    friend72 = Friend(user_to=14, user_from=15, status="FRIENDS")
    friend73 = Friend(user_to=16, user_from=15)
    friend74 = Friend(user_to=17, user_from=15)
    friend75 = Friend(user_to=18, user_from=15, status="FRIENDS")

    friend76 = Friend(user_to=13, user_from=16)
    friend77 = Friend(user_to=14, user_from=16, status="FRIENDS")
    friend78 = Friend(user_to=15, user_from=16)
    friend79 = Friend(user_to=17, user_from=16)
    friend80 = Friend(user_to=18, user_from=16)

    friend81 = Friend(user_to=13, user_from=17, status="FRIENDS")
    friend82 = Friend(user_to=14, user_from=17, status="FRIENDS")
    friend83 = Friend(user_to=15, user_from=17)
    friend84 = Friend(user_to=16, user_from=17)
    friend85 = Friend(user_to=18, user_from=17)

    friend86 = Friend(user_to=13, user_from=18)
    friend87 = Friend(user_to=14, user_from=18)
    friend88 = Friend(user_to=15, user_from=18, status="FRIENDS")
    friend89 = Friend(user_to=16, user_from=18)
    friend90 = Friend(user_to=17, user_from=18)

    db.session.add(friend1)
    db.session.add(friend2)
    db.session.add(friend3)
    db.session.add(friend4)
    db.session.add(friend5)
    db.session.add(friend6)
    db.session.add(friend7)
    db.session.add(friend8)
    db.session.add(friend9)
    db.session.add(friend10)
    db.session.add(friend11)
    db.session.add(friend12)
    db.session.add(friend13)
    db.session.add(friend14)
    db.session.add(friend15)
    db.session.add(friend16)
    db.session.add(friend17)
    db.session.add(friend18)
    db.session.add(friend19)
    db.session.add(friend20)
    db.session.add(friend21)
    db.session.add(friend22)
    db.session.add(friend23)
    db.session.add(friend24)
    db.session.add(friend25)
    db.session.add(friend26)
    db.session.add(friend27)
    db.session.add(friend28)
    db.session.add(friend29)
    db.session.add(friend30)
    db.session.add(friend31)
    db.session.add(friend32)
    db.session.add(friend33)
    db.session.add(friend34)
    db.session.add(friend35)
    db.session.add(friend36)
    db.session.add(friend37)
    db.session.add(friend38)
    db.session.add(friend39)
    db.session.add(friend40)
    db.session.add(friend41)
    db.session.add(friend42)
    db.session.add(friend43)
    db.session.add(friend44)
    db.session.add(friend45)
    db.session.add(friend46)
    db.session.add(friend47)
    db.session.add(friend48)
    db.session.add(friend49)
    db.session.add(friend50)
    db.session.add(friend51)
    db.session.add(friend52)
    db.session.add(friend53)
    db.session.add(friend54)
    db.session.add(friend55)
    db.session.add(friend56)
    db.session.add(friend57)
    db.session.add(friend58)
    db.session.add(friend59)
    db.session.add(friend60)
    db.session.add(friend61)
    db.session.add(friend62)
    db.session.add(friend63)
    db.session.add(friend64)
    db.session.add(friend65)
    db.session.add(friend66)
    db.session.add(friend67)
    db.session.add(friend68)
    db.session.add(friend69)
    db.session.add(friend70)
    db.session.add(friend71)
    db.session.add(friend72)
    db.session.add(friend73)
    db.session.add(friend74)
    db.session.add(friend75)
    db.session.add(friend76)
    db.session.add(friend77)
    db.session.add(friend78)
    db.session.add(friend79)
    db.session.add(friend80)
    db.session.add(friend81)
    db.session.add(friend82)
    db.session.add(friend83)
    db.session.add(friend84)
    db.session.add(friend85)
    db.session.add(friend86)
    db.session.add(friend87)
    db.session.add(friend88)
    db.session.add(friend89)
    db.session.add(friend90)

    db.session.commit()


def undo_friends():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.friends RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM friends"))

    db.session.commit()
