"""empty message

<<<<<<< HEAD:backend/migrations/versions/5af340d26e99_.py
Revision ID: 5af340d26e99
Revises: 
Create Date: 2023-07-28 16:24:07.769201
=======
Revision ID: 80da5db844f1
Revises: 
Create Date: 2023-07-28 19:19:09.662536
>>>>>>> 609b8d38c32510990c72fc10d9bf9d7b857b2049:backend/migrations/versions/80da5db844f1_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:backend/migrations/versions/5af340d26e99_.py
revision = '5af340d26e99'
=======
revision = '80da5db844f1'
>>>>>>> 609b8d38c32510990c72fc10d9bf9d7b857b2049:backend/migrations/versions/80da5db844f1_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('birthday', sa.String(length=12), nullable=False),
    sa.Column('banner_color', sa.String(length=7), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('pronouns', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    op.drop_table('direct_messages')
    op.drop_table('users')
    # ### end Alembic commands ###
